- README.md
- docs/contributing.md
when following README as is, I ran into a `no such file or directory` error when attempting the build step. 
```
➜  simkube git:(master) make build
Makefile:19: build/base.mk: No such file or directory
make: *** No rule to make target `build/base.mk'.  Stop.
```
add in `git submodule init` and `git submodule update` to building section in README.md to fix build file missing error when setting up simkube.
with all prerequisites installed as listed in the README:
- created test directory 
- cloned simkube
- ran `git init submodule`, `git init update`, `make build`, and `make skctl` from the root directory
```
➜  simkube git:(master) git submodule init
Submodule 'build' (https://github.com/acrlabs/build-scripts) registered for path 'build'
➜  simkube git:(master) git submodule update …
```
> Update README.md with git submodule commands

- README.md
- docs/contributing.md
1. Updated link in contributing.md to point to golangci-lint's website (it was pointing to the website for the pre-commt project).
2. Updated existing warning in README.md regarding auto-generated code. I simply added a Warning admonition command in Markdown to make this more easily stand out to the reader. 
Basic documentation update to fix a link that redirects the reader to a resource not related to the link itself (goes to pre-commit instead of the link's text: golangci-lint)
> - How did you test your changes?
> 1. Committed my code to my fork of the project, then clicked the link and checked that it routed me to golangci-lint.run from GitHub's markdown viewer. 
> 2. Also visually verified that the Warning admonition appears in the README.md file
> - Does this code require any new …
> Update contributing.md with appropriate link to golangci-lint

- cli/args.rs
- cli/run.rs
- cli/snapshot.rs
- ctrl/controller.rs
- ctrl/objects.rs
- ctrl/tests/controller_test.rs
- driver/main.rs
- k8s/poetry.lock
- k8s/raw/simkube.io_simulations.yml
- src/api/v1/simulations.rs
- src/store/tests/import_export_test.rs
- src/store/trace_store.rs
- src/time.rs
- src/watch/dyn_obj_watcher.rs
- src/watch/pod_watcher.rs
- fix `skctl snapshot` hang (I think)
- fix `sk-tracer` panics if the channel receivers go away
- fix SimulationStatus updates if the Job completes successfully
- update the Simulation spec to add a duration field
- move the duration arg from `skctl snapshot` to `skctl run`, which makes more sense
- make test (with a few new tests)
> skctl run now specifies duration, plus some bug fixes

- driver/runner.rs
- src/k8s/pod_ext.rs
It is possible to _create_ a container with two different ports referencing the same port number, but you can't apply a patch to that pod later, even if you're not changing the port definitions.  So in the short term we're just stripping port definitions from the podspec during the simulation.
One could make the argument that we should just strip them from the trace entirely but my working hypothesis is that it's better to leave them in the trace data and let the consumers of the trace figure out what to do with it?  But that requires us to make changes in two different places whenever we touch the pod spec in the simulation -- this impacts the hash we compute for the pod object, so we end up having to make changes in two places at once.
I'd like to maybe have a test for this, but it's …
> drop ports when running sim

- Cargo.lock
- Cargo.toml
- lib/store/trace_store.rs
- Adds some logging around import/export timestamps, references a fork of `parse_datetime` with a fixed duration parsing routing (will want to remove the fork when [the fix](https://github.com/uutils/parse_datetime/pull/80) is merged).
- `make test`
- manual testing by changing my laptop local time
> reference parse_datetime fork, update logging with timestamps

- Cargo.lock
- Cargo.toml
- ctrl/controller.rs
- driver/runner.rs
- driver/tests/runner_test.rs
- lib/constants.rs
- lib/k8s/lease.rs
- lib/k8s/tests/lease_test.rs
- lib/k8s/util.rs
Waits until the driver has fully cleaned up the old simulation before starting a new one
- `make test` -- new tests covering the cleanup function in the driver
Resolves #113
> add cleanup delay to driver

- Makefile
- ctrl/controller.rs
- ctrl/objects.rs
- ctrl/tests/controller_test.rs
- driver/runner.rs
- lib/k8s/lease.rs
- lib/k8s/tests/lease_test.rs
- lib/sim/mod.rs
- lib/time.rs
- lib/watch/dyn_obj_watcher.rs
- lib/watch/pod_watcher.rs
- Fix the "retry" bug -- if the simulation PostStop hooks failed for whatever reason (e.g., if they're trying to clean up and the thing they're cleaning up is already gone), the simulation would get into an endless retry loop.  We move the PostStop hooks logic into `cleanup_simulation` and move the PreStart hooks logic into `setup_simulation` for parallelity, which is totally a word.
- If multiple sims were scheduled simultaneously, it never _actually_ returned `Blocked` for the simulation state.  We now check for (and try to claim) the lease in `fetch_driver_status` instead of `setup_simulation` to fix this bug.
- Manual testing
- new tests added
> fix retry bug and blocking bug

- docs/intro/running.md
This is what appears in the [documentation](https://appliedcomputing.io/simkube/docs/intro/running/#step-3-run-your-simulation):
```
> skctl run my-first-simulation --trace-path s3://your-simkube-bucket/path/to/trace +5m
```
Reproducing as faithfully as I can with local storage, preserving the trace-path to preserve duration argument position:
```
> skctl run my-first-simulation --trace-path file:///data/trace +5m
error: unexpected argument '+5m' found
```
Duration is a named argument (see sk-cli/src/run.rs:27) and clap doesn't to my knowledge accept named arguments as positional without weird builder hacks, but the repo uses clap derive, so I think this is an error in the documentation.
This PR changes the documentation to explicitly name the duration argument.
> Fix: specify duration as a named argument in skctl run documentation.

- Cargo.lock
- Cargo.toml
- sk-core/src/external_storage.rs
- sk-ctrl/Cargo.toml
- sk-ctrl/src/objects.rs
- sk-tracer/src/main.rs
- sk-tracer/src/tests/tracer_test.rs
object_store made the ObjectStoreScheme enum public so we don't have to roll our own any more
- make test
> remove custom object store code

- Cargo.lock
- Cargo.toml
- Makefile
- docs/intro/installation.md
- images/Dockerfile.sk-ctrl
- images/Dockerfile.sk-driver
- images/Dockerfile.sk-tracer
- sk-core/Cargo.toml
- sk-core/src/external_storage.rs
Local path resolution in the driver and skctl no longer requires the `file:///` prefix
- Manual testing
- new tests added
> handle local paths without file:///

- Cargo.lock
- Cargo.toml
- k8s/kustomize/prod/sk-tracer.yml
- k8s/sk_tracer.py
- sk-cli/src/export.rs
- sk-core/src/k8s/gvk.rs
- sk-driver/src/runner.rs
- sk-driver/src/tests/data/trace.json
- sk-driver/src/tests/runner_test.rs
- sk-store/src/config.rs
- sk-store/src/tests/trace_store_test.rs
- Make the podSpecTemplatePath field optional, so that things like ServiceAccounts and ConfigMaps can be traced
- make the leading '/' in the GVK string optional
- fix regression in deleting objects on simulation replay
- Tests added for GVK ser/de
- Test added for sim runner that catches the regression
Related to #137
> Updates to trace config format as well as bugfix in sim runner

- sk-store/src/trace_store.rs
Update the tracer log lines to include the Kind of the object that it's tracking
> fix: print object kind in tracer log

- .github/workflows/k8s_plan.yml
- .github/workflows/verify.yml
Cancel old versions of the "verify/k8s_plane" workflows when updates to the PR are pushed
> ci: cancel old versions of verify workflow

- Cargo.lock
- Cargo.toml
- examples/tracer_config.yml
- sk-cli/src/snapshot.rs
- sk-core/Cargo.toml
- sk-core/src/external_storage.rs
- sk-core/src/k8s/pod_lifecycle.rs
- sk-core/src/k8s/testutils/fake.rs
- sk-core/src/time.rs
- sk-ctrl/src/objects.rs
- sk-driver/Cargo.toml
- sk-driver/src/mutation.rs
- sk-driver/src/tests/mutation_test.rs
- sk-store/Cargo.toml
- sk-store/src/tests/import_export_test.rs
- sk-store/src/watchers/dyn_obj_watcher.rs
- sk-store/src/watchers/mod.rs
- sk-store/src/watchers/pod_watcher.rs
- sk-store/src/watchers/tests/mod.rs
- sk-store/src/watchers/tests/pod_watcher_test.rs
- sk-tracer/src/main.rs
Update all dependencies; this necessitated some changes to the tracer to conform to the new Event enum in kube-rs.
- make test
> chore: upgrade complete

- sk-cli/src/xray/view/helpers.rs
- sk-cli/src/xray/view/tests/snapshots/skctl__xray__view__tests__view_test__itest_render_event_list_event_selected@2.snap
We double-counted columns in the error view when determining how much to truncate for the item name display in skctl xray, which led names getting truncated when they shouldn't have been.
- it'd be sorta nice to have a snapshot test for this since the other snapshot tests didn't catch it, but it's kindof a pain to do so I didn't bother.
> fix: misaligned error display in skctl xray

- sk-cli/src/validation/annotated_trace.rs
- sk-cli/src/validation/mod.rs
- sk-cli/src/validation/rules/mod.rs
- sk-cli/src/validation/rules/status_field_populated.rs
- sk-cli/src/validation/rules/tests/mod.rs
- sk-cli/src/validation/rules/tests/status_field_populated_test.rs
- sk-cli/src/validation/tests/annotated_trace_test.rs
- sk-cli/src/validation/tests/mod.rs
- sk-cli/src/validation/tests/validation_store_test.rs
- sk-cli/src/validation/validation_store.rs
- sk-cli/src/validation/validator.rs
- sk-cli/src/xray/view/helpers.rs
`Annotations` in `skctl validate` include a set of possible patches per event/object, instead of just an error code and affected index.  This is because some proposed fixes are going to be specific to the specific state/object affected.
- make test
> feat: annotations in `skctl validate` include possible patches

- .pre-commit-config.yaml
- Makefile
- sk-cli/src/validation/README.md
- sk-cli/src/validation/annotated_trace.rs
- sk-cli/src/validation/rules/README.md
- sk-cli/src/validation/rules/mod.rs
- sk-cli/src/validation/rules/service_account_missing.rs
- sk-cli/src/validation/rules/status_field_populated.rs
- sk-cli/src/validation/rules/tests/mod.rs
- sk-cli/src/validation/rules/tests/service_account_missing_test.rs
- sk-cli/src/validation/rules/tests/status_field_populated_test.rs
- sk-cli/src/validation/tests/mod.rs
- sk-cli/src/validation/validation_store.rs
- sk-cli/src/validation/validator.rs
- sk-core/src/constants.rs
- sk-core/src/k8s/testutils/objs.rs
Add a validation rule to check if the service account for pods exists
- new tests for the service_account_exists rule
> check for service account existing in validation

- .gitignore
Please describe what this PR does
- How did you test your changes?
- Does this code require any new tests to be written?
Resolves #xxxx
> chore: add .jj to .gitignore

- Cargo.lock
- Cargo.toml
- rust-coverage.lcov
- sk-cli/src/validation/annotated_trace.rs
- sk-cli/src/validation/rules/service_account_missing.rs
- sk-cli/src/validation/rules/tests/mod.rs
- sk-cli/src/validation/rules/tests/service_account_missing_test.rs
- sk-cli/src/validation/tests/annotated_trace_test.rs
- sk-cli/src/validation/tests/mod.rs
- sk-cli/src/xray/view/tests/snapshots/skctl__xray__view__tests__view_test__itest_render_event_list@0.snap
- sk-cli/src/xray/view/tests/snapshots/skctl__xray__view__tests__view_test__itest_render_event_list@3.snap
- sk-cli/src/xray/view/tests/snapshots/skctl__xray__view__tests__view_test__itest_render_event_list_event_selected@0.snap
- sk-cli/src/xray/view/tests/snapshots/skctl__xray__view__tests__view_test__itest_render_event_list_event_selected@2.snap
- sk-cli/src/xray/view/tests/snapshots/skctl__xray__view__tests__view_test__itest_render_event_list_event_selected@3.snap
- sk-core/Cargo.toml
- sk-core/src/constants.rs
- sk-core/src/k8s/testutils/objs.rs
- sk-store/src/lib.rs
- Adds the `InsertAt` patch location for annotations
- Updates the service_account_missing check to use this patch location as a secondary patch alternative
- make test (new tests added for InsertAt)
> feat: InsertAt patch location + secondary patch for service_account_missing

- sk-core/src/k8s/util.rs
- sk-ctrl/src/objects.rs
- testutils/src/pods.rs
`get_or_insert_default` is stabilized now, let's use it
- `make test`
> refactor: use get_or_insert_default

- sk-store/src/watchers/mod.rs
- sk-store/src/watchers/pod_watcher.rs
If there are pods that show up that are owned by something that `sk-tracer` doesn't have permissions to watch, previously it would stacktrace and make it look like the program had crashed.  This should still be an error, but let's not make it stacktrace since `sk-tracer` can keep going with other events.
> fix: error messages don't stacktrace for 'recoverable' tracer errors

- .github/workflows/verify.yml
Remove codecov token to let dependabot still work (see details in [the readme](https://github.com/codecov/codecov-action?tab=readme-ov-file), v4 and v5 releases).
> chore: bump codecov version

- sk-store/src/event_list.rs
- sk-store/src/store.rs
- sk-store/src/tests/trace_store_test.rs
`export_all` used end_ts, which is the last timestamp of an event in the trace; but export is end-ts-exclusive, so we need to add one here.
- make test
> fix: export_all off-by-one error

- .github/workflows/verify.yml
- .pre-commit-config.yaml
- docs/dev/setup.md
- hack/fmt
Pin Rust nightly version so we don't get lints/checks failing that don't match local
> ci: pin nightly version
